#!/usr/bin/env bash

# Add initial repo
echo -e "\n[archstrike]\nServer = https://mirror.archstrike.org/\$arch/\$repo" | tee -a /etc/pacman.conf
pacman -Syy

# Install ArchStrike keyring
pacman-key --init
dirmngr < /dev/null
pacman-key -r 9D5F1C051D146843CDA4858BDE64825E7CBC0D51
pacman-key --lsign-key 9D5F1C051D146843CDA4858BDE64825E7CBC0D51

# Install keyring and mirrorlist packages
pacman -S archstrike-keyring --noconfirm
pacman -S archstrike-mirrorlist --noconfirm

# Configure pacman to use the mirrorlist
sed -i 's|Server = https://mirror.archstrike.org/\$arch/\$repo|Include = /etc/pacman.d/archstrike-mirrorlist|' /etc/pacman.conf
