#!/usr/bin/env bash

# Variables
funcpath="$(pwd)/functions"

case "$1" in
  test)
      . "${funcpath}/test.func"
      [ -z "$2" ] && yopkg_error_dump
      yodump "$2"
      ;;
  pkg)
      . "${funcpath}/pkg.func"
      [ -z "$2" ] && yopkg_error_dump
      [ "$2" = git ] && cupgit
      [ "$2" = chroot ] && cupchroot
      ;;
  chroot)
      . "${funcpath}/chroot.func"
      [ "$2" = build ] && build
      [ "$2" = update ] && update
      ;;
  *)
      . "${funcpath}/help.func"
esac
